[functions]
  external_node_modules = ["express","bcrypt"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
  
[build]
  functions = "functions"
  node_bundler = "esbuild"

 