// constants.js

// Success
const HTTP_OK = 200;
const HTTP_CREATED = 201;
const HTTP_ACCEPTED = 202;

// Redirection
const HTTP_MOVED_PERMANENTLY = 301;
const HTTP_FOUND = 302;
const HTTP_SEE_OTHER = 303;

// Client Errors
const INCORRECT_PASSWORD = 400;
const HTTP_UNAUTHORIZED = 401;
const USER_ALREADY_EXIST = 403;
const NO_USER_FOUND = 404;

// Server Errors
const HTTP_INTERNAL_SERVER_ERROR = 500;
const HTTP_NOT_IMPLEMENTED = 501;
const HTTP_BAD_GATEWAY = 502;

module.exports = {
    HTTP_OK,
    HTTP_CREATED,
    HTTP_ACCEPTED,
    HTTP_MOVED_PERMANENTLY,
    HTTP_FOUND,
    HTTP_SEE_OTHER,
    HTTP_UNAUTHORIZED,

    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_NOT_IMPLEMENTED,
    HTTP_BAD_GATEWAY,
    NO_USER_FOUND,
    USER_ALREADY_EXIST,
    INCORRECT_PASSWORD,
};
